FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8082

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore EnterpriseWebApi.API/EnterpriseWebApi.API.csproj
RUN dotnet publish EnterpriseWebApi.API/EnterpriseWebApi.API.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "EnterpriseWebApi.API.dll"]
